### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by chraibi** [sylvain-faure/cromosim#1]
Thanks for releasing this interesting project. 
I wonder if there is somewhere a "get started" demo. 

I saw some nice simulations. Maybe describe in the readme the steps how to reproduce them.

**Comment by HanoCat** [comment]
Hi chraibi, 
It is almost two years now since you left this comment.. did you make it ? 
if yes, I have some questions too in this project and in crowd in general, I'll appreciate your answers.. 

Have a great day
Hano

**Comment by chraibi** [comment]
Hi Hano,
it seems this issue can be closed. The README gets you started.

<img width="599" alt="Screen Shot 2022-01-10 at 21 00 35" src="https://user-images.githubusercontent.com/5772973/148831195-20cb82f6-1e36-4407-a52f-c5a30ed6f599.png">


<img width="1320" alt="Screen Shot 2022-01-10 at 20 59 11" src="https://user-images.githubusercontent.com/5772973/148831120-6868e375-6284-4c29-828e-98b9e96684a2.png">
